# Generated by Django 3.1 on 2020-08-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('supplier', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=200)),
                ('code', models.CharField(default='n/a', max_length=200)),
                ('quantity', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('out', 'checked out'), ('in', 'checked in')], max_length=50, null=True)),
                ('due_back', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
