# Generated by Django 3.1 on 2020-08-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
