# Generated by Django 3.1 on 2020-08-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanagement', '0002_auto_20200824_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='checkout_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
