# Generated by Django 3.1 on 2020-08-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanagement', '0003_bottle_checkout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='status',
            field=models.CharField(blank=True, choices=[('out', 'checked out'), ('in', 'checked in')], max_length=50, null=True),
        ),
    ]
