# Generated by Django 3.1 on 2020-08-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanagement', '0004_auto_20200825_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='borrower_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bottle',
            name='borrower_full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bottle',
            name='borrower_group',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
