# Generated by Django 3.1 on 2020-08-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanagement', '0005_auto_20200826_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='borrower_group',
            field=models.CharField(blank=True, choices=[('BOD', 'Bode'), ('CAR', 'Carreira'), ('CHE', 'Chen'), ('DIE', 'Diederich'), ('EBE', 'Ebert'), ('HIL', 'Hilvert'), ('KAS', 'Kast'), ('MOR', 'Morandi'), ('THI', 'Thilgen'), ('WEN', 'Wennemers'), ('YAM', 'Yamakoshi'), ('ZEN', 'Zenobi'), ('OTH', 'OTHER')], max_length=3, null=True),
        ),
    ]
