# Generated by Django 3.1 on 2020-08-26 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanagement', '0006_auto_20200826_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottle',
            name='return_date',
        ),
        migrations.AlterField(
            model_name='bottle',
            name='borrower_full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Borrower full name'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='due_back',
            field=models.DateField(blank=True, default=datetime.date(2020, 8, 26), null=True),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Bottle code'),
        ),
    ]
