# Generated by Django 3.1 on 2020-08-26 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanagement', '0007_auto_20200826_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='borrower_email',
            field=models.EmailField(blank=True, help_text='Please use your ETH email address', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='checkout_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='due_back',
            field=models.DateField(blank=True, default=datetime.date(2020, 8, 26), help_text='Enter a date between now and 2 weeks (default 3 days).', null=True),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='status',
            field=models.CharField(blank=True, choices=[('out', 'checked out'), ('in', 'checked in')], max_length=3, null=True),
        ),
    ]
