# Generated by Django 3.1 on 2020-08-26 16:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanagement', '0008_auto_20200826_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='due_back',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 26, 16, 25, 53, 258355, tzinfo=utc), help_text='Enter a date between now and 2 weeks (default 3 days).', null=True),
        ),
    ]
