# Generated by Django 3.1 on 2020-08-26 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanagement', '0009_auto_20200826_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='due_back',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='Enter a date between now and 2 weeks (default 3 days).', null=True),
        ),
    ]
