# Generated by Django 3.1 on 2020-08-27 09:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanagement', '0010_auto_20200826_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='borrower_group',
            field=models.CharField(blank=True, choices=[('Bode', 'Bode'), ('Carreira', 'Carreira'), ('Chen', 'Chen'), ('Diederich', 'Diederich'), ('Ebert', 'Ebert'), ('Hilvert', 'Hilvert'), ('Kast', 'Kast'), ('Morandi', 'Morandi'), ('Thilgen', 'Thilgen'), ('Wennemers', 'Wennemers'), ('Yamakoshi', 'Yamakoshi'), ('Zenobi', 'Zenobi'), ('other', 'OTHER')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='due_back',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 30, 9, 47, 14, 312645, tzinfo=utc), help_text='Enter a date between now and 2 weeks (default 3 days).', null=True, verbose_name='Anticipated return date'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='status',
            field=models.CharField(blank=True, choices=[('out', 'checked out'), ('in', 'checked in'), ('empty', 'EMPTY')], max_length=5, null=True),
        ),
    ]
