# Generated by Django 3.1 on 2020-08-31 16:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import inventorymanagement.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanagement', '0025_auto_20200828_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='borrower_email',
            field=models.EmailField(blank=True, help_text='Please use your ETH email address', max_length=100, null=True, validators=[inventorymanagement.validators.validate_ethz_email_address]),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='due_back',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 3, 16, 0, 36, 599208, tzinfo=utc), help_text='Enter a date between now and 2 weeks (default 3 days).', null=True, validators=[inventorymanagement.validators.validate_two_week_checkout_limit, inventorymanagement.validators.validate_due_back_not_in_past], verbose_name='Anticipated return date'),
        ),
    ]
