# Generated by Django 3.1.1 on 2020-11-23 14:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import inventorymanagement.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanagement', '0031_auto_20201123_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='due_back',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 11, 26, 14, 28, 24, 769841, tzinfo=utc), help_text='Enter a date between now and 2 weeks (default 3 days).', null=True, validators=[inventorymanagement.validators.validate_two_week_checkout_limit, inventorymanagement.validators.validate_due_back_not_in_past], verbose_name='Anticipated return date'),
        ),
    ]
