# Generated by Django 3.1.1 on 2021-05-27 12:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import inventorymanagement.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanagement', '0032_auto_20201123_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='borrower_group',
            field=models.CharField(blank=True, choices=[('Bode', 'Bode'), ('Carreira', 'Carreira'), ('Chen', 'Chen'), ('Diederich', 'Diederich'), ('Ebert', 'Ebert'), ('Hilvert', 'Hilvert'), ('Kast', 'Kast'), ('Lang', 'Lang'), ('Lehrlabor', 'Lehrlabor'), ('Morandi', 'Morandi'), ('Thilgen', 'Thilgen'), ('Wennemers', 'Wennemers'), ('Yamakoshi', 'Yamakoshi'), ('Zenobi', 'Zenobi'), ('other', 'OTHER')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='due_back',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 5, 30, 12, 32, 19, 306591, tzinfo=utc), help_text='Enter a date between now and 2 weeks (default 3 days).', null=True, validators=[inventorymanagement.validators.validate_two_week_checkout_limit, inventorymanagement.validators.validate_due_back_not_in_past], verbose_name='Anticipated return date'),
        ),
    ]
