# Generated by Django 3.2.5 on 2021-07-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanagement', '0036_alter_bottle_due_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='borrower_full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Borrower full name'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='borrower_group',
            field=models.CharField(blank=True, choices=[('Bode', 'Bode'), ('Carreira', 'Carreira'), ('Chen', 'Chen'), ('Ebert', 'Ebert'), ('Hilvert', 'Hilvert'), ('Kast', 'Kast'), ('Lang', 'Lang'), ('Lehrlabor', 'Lehrlabor'), ('Morandi', 'Morandi'), ('Thilgen', 'Thilgen'), ('Wennemers', 'Wennemers'), ('Yamakoshi', 'Yamakoshi'), ('Zenobi', 'Zenobi'), ('other', 'OTHER')], max_length=12, null=True),
        ),
    ]
