# Generated by Django 3.2.5 on 2021-07-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanagement', '0037_auto_20210712_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='borrower_group',
            field=models.CharField(blank=True, choices=[('Bode', 'Bode'), ('Carreira', 'Carreira'), ('Chen', 'Chen'), ('Ebert', 'Ebert'), ('Hilvert', 'Hilvert'), ('Kast', 'Kast'), ('Lang', 'Lang'), ('Lehrlabor', 'Lehrlabor'), ('Morandi', 'Morandi'), ('Thilgen', 'Thilgen'), ('Wennemers', 'Wennemers'), ('Yamakoshi', 'Yamakoshi'), ('Zenobi', 'Zenobi'), ('other', 'OTHER')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='description',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='id',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Bottle code'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='owner',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='price',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='quantity',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='supplier',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
