# Generated by Django 3.2.5 on 2021-07-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanagement', '0038_auto_20210715_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='code',
            field=models.CharField(default='n/a', max_length=200, verbose_name='owner code'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='owner_group',
            field=models.CharField(default='n/a', max_length=4),
            preserve_default=False,
        ),
    ]
