# Generated by Django 3.2.5 on 2021-07-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanagement', '0039_auto_20210716_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeListEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(help_text='Enter a short description of the recorded change (max. 200 characters)', max_length=200)),
            ],
        ),
    ]
