# Generated by Django 3.2.5 on 2021-07-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanagement', '0040_changelistentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changelistentry',
            name='id',
        ),
        migrations.AddField(
            model_name='changelistentry',
            name='entry_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
