# Generated by Django 3.2.5 on 2021-07-16 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanagement', '0041_auto_20210716_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelistentry',
            name='date',
            field=models.DateField(default=datetime.date(2021, 7, 16)),
        ),
    ]
