# Generated by Django 3.2.5 on 2021-07-16 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanagement', '0042_alter_changelistentry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelistentry',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
